name: Lint application

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Lint code
        uses: actions/golangci-lint-action@main
        with:
          version: v9.3.0
